--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2/28/2021 4:59:04 PM
-- Server version: 5.5.5-10.1.47-MariaDB-0ubuntu0.18.04.1
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE test;

--
-- Drop procedure `Proc_GetDatas`
--
DROP PROCEDURE IF EXISTS Proc_GetDatas;

--
-- Drop procedure `Proc_InsertData`
--
DROP PROCEDURE IF EXISTS Proc_InsertData;

--
-- Drop table `Data`
--
DROP TABLE IF EXISTS Data;

--
-- Set default database
--
USE test;

--
-- Create table `Data`
--
CREATE TABLE Data (
  dataId char(36) NOT NULL,
  merchantId varchar(255) DEFAULT NULL COMMENT 'Mã nhà cung cấp',
  amount varchar(255) DEFAULT NULL COMMENT 'Số tiền thanh toán',
  creationTime datetime DEFAULT NULL COMMENT 'Thời gian thanh toán',
  currency varchar(255) DEFAULT NULL COMMENT 'Loại tiền thanh toán',
  id varchar(255) DEFAULT NULL COMMENT 'Id đơn hàng',
  result varchar(255) DEFAULT NULL COMMENT 'Trạng thái thanh toán',
  nameOnCard varchar(255) DEFAULT NULL COMMENT 'Tên chủ thẻ',
  issueDate varchar(255) DEFAULT NULL COMMENT 'tháng năm đăng ký ddyy',
  number varchar(255) DEFAULT NULL COMMENT 'Số thẻ',
  date datetime DEFAULT NULL COMMENT 'Thời gian hoàn thành thanh toán',
  dateCreated datetime DEFAULT NULL COMMENT 'ngày giờ tạo bản ghi',
  PRIMARY KEY (dataId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 564,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

DELIMITER $$

--
-- Create procedure `Proc_InsertData`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_InsertData (IN dataId char(36), IN merchantId varchar(255), IN amount varchar(255), IN creationTime datetime, IN currency varchar(255), IN id varchar(255), IN result varchar(255), IN nameOnCard varchar(255), IN issueDate varchar(255), IN number varchar(255), IN date datetime, IN dateCreated datetime)
BEGIN
  INSERT INTO Data (dataId, merchantId, amount, creationTime, currency, id, result, nameOnCard, issueDate, number, date, dateCreated)
    VALUES (UUID(), merchantId, amount, creationTime, currency, id, result, nameOnCard, issueDate, number, date, NOW());
END
$$

--
-- Create procedure `Proc_GetDatas`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetDatas ()
BEGIN
  SELECT
    *
  FROM Data d
  ORDER BY d.dateCreated DESC;
END
$$

DELIMITER ;

-- 
-- Dumping data for table Data
--
INSERT INTO Data VALUES
('11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Merchant77578', '5956897', '2020-09-30 09:19:49', 'VND', 'ORD_43827', 'SUCCESS', 'Archer', '8276', '73577578', '1980-01-25 22:20:38', NULL),
('142cb08f-7c31-21fa-8e90-67245e8b283e', 'Merchant17553', '5487923', '1970-01-01 00:07:13', 'VND', 'ORD_03549', 'SUCCESS', 'Boucher', '8046', '94630114', '1970-01-01 00:00:04', NULL),
('17120d02-6ab5-3e43-18cb-66948daf6128', 'Merchant57052', '1657187', '2019-01-07 15:50:20', 'VND', 'ORD_97292', 'SUCCESS', 'Lang', '8490', '34927343', '2007-05-21 19:09:55', NULL),
('1ded3dd7-32db-5bc9-9190-67245e8b283e', 'Merchant63320', NULL, NULL, NULL, 'ORD_08990', NULL, NULL, NULL, NULL, NULL, NULL),
('1f74cd3f-6de4-5324-0180-e8e2a817c80e', 'Merchant10030', '1523255', '1970-01-01 00:00:05', 'VND', 'ORD_89089', 'SUCCESS', 'Abraham', '8400', '4079750', '1970-01-01 00:56:40', NULL),
('284ccb05-337b-7e6f-9090-67245e8b283e', 'Merchant74663', '3568109', '2008-01-26 11:31:09', 'VND', 'ORD_95490', 'SUCCESS', 'Clarkson', '9379', '17966002', '1970-01-01 00:00:25', NULL),
('2bbbd485-6df2-536a-7e32-6a1673ffca7c', 'Merchant32426', '1822739', '1970-01-01 00:01:04', 'VND', 'ORD_12252', 'SUCCESS', 'Almeida', '8644', '27887987', '2020-07-31 16:22:04', NULL),
('2dcedb9c-6c32-7d27-977d-e8c757976496', 'Merchant64024', '5706715', '1984-06-23 13:09:20', 'VND', 'ORD_85449', 'SUCCESS', 'Carrier', '8916', '20928641', '2013-03-25 22:58:01', NULL),
('4577565a-7e3e-493a-74dd-867949feb8b5', 'Merchant65638', '5947305', '1977-12-25 07:25:51', 'VND', 'ORD_65532', 'SUCCESS', 'Stephenson', '3687', '43438961', '1975-03-16 16:53:17', NULL),
('469b3ece-744a-45d5-957d-e8c757976496', 'Merchant31969', '4821977', '2013-11-10 09:30:52', 'VND', 'ORD_48524', 'SUCCESS', 'Guyton', '192', '50082423', '2002-01-25 09:49:39', NULL),
('4760d71f-6e2f-5b32-19cb-66948daf6128', 'Merchant70936', '2972686', '1978-06-28 23:13:24', 'VND', 'ORD_80091', 'SUCCESS', 'Holloman', '4963', '96848619', '1989-06-29 12:08:54', NULL),
('4d7b21db-2e02-12b7-a9db-e5d54223c257', 'Merchant46140', '2933140', '1970-01-01 00:15:42', 'VND', 'ORD_03876', 'SUCCESS', 'Crandall', '5705', '40214709', '1983-11-05 02:48:41', NULL),
('4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Merchant44670', '4585104', '1997-06-15 11:21:38', 'VND', 'ORD_07879', 'SUCCESS', 'Bolt', '2286', '49587670', '1970-01-01 00:00:08', NULL),
('52bcea9c-79a3-11eb-8a1f-00163e047e89', 'DucBinh4', '5956897', '2020-09-30 09:19:49', 'VND', 'ORD_43827', 'SUCCESS', 'Archer', '8276', '73577578', '1980-01-25 22:20:38', '2021-02-28 16:59:53'),
('5660d465-6020-48f3-75dd-867949feb8b5', 'Merchant96411', '2362031', '2015-02-07 00:31:42', 'VND', 'ORD_42925', 'SUCCESS', 'Crockett', '4115', '50070957', '1970-01-01 00:06:55', NULL),
('59d19422-6657-452e-a7db-e5d54223c257', 'Merchant29149', NULL, NULL, NULL, 'ORD_20373', NULL, NULL, NULL, '48405384', '1995-05-19 16:18:32', NULL),
('5b2fcdf5-2050-7cb2-8f90-67245e8b283e', 'Merchant03014', '3191244', '1994-11-19 10:04:13', 'VND', 'ORD_28469', 'SUCCESS', 'Sterling', '1587', '54770936', '1970-01-01 00:10:39', NULL),
('5cd275f9-79a3-11eb-8a1f-00163e047e89', 'DucBinh4', '5956897', '2020-09-30 09:19:49', 'VND', 'ORD_43827', 'SUCCESS', 'Archer', '8276', '73577578', '1980-01-25 22:20:38', '2021-02-28 17:00:10'),
('5ee06366-799e-11eb-8a1f-00163e047e89', 'Merchant77578', '5956897', '2020-09-30 09:19:49', 'VND', 'ORD_43827', 'SUCCESS', 'Archer', '8276', '73577578', '1980-01-25 22:20:38', '2021-02-28 16:24:26'),
('68478414-705a-2626-5c92-08c864661f9c', 'Merchant12198', '5087299', '1994-06-25 01:49:19', 'VND', 'ORD_59293', 'SUCCESS', 'Morehead', '9375', '93049894', '1984-11-26 13:17:48', NULL),
('6d471f60-799e-11eb-8a1f-00163e047e89', 'DucBinh1', '5956897', '2020-09-30 09:19:49', 'VND', 'ORD_43827', 'SUCCESS', 'Archer', '8276', '73577578', '1980-01-25 22:20:38', '2021-02-28 16:24:51'),
('7686595d-16d5-33b3-0080-e8e2a817c80e', 'Merchant49360', '4724768', '1976-05-14 19:53:41', 'VND', 'ORD_42576', 'SUCCESS', 'Seiler', '6747', '39993997', '2005-10-16 03:28:09', NULL),
('768f8e64-7d10-20c9-967d-e8c757976496', 'Merchant94617', '5152838', '1972-07-28 01:17:26', 'VND', 'ORD_09385', 'SUCCESS', 'Crane', '2300', NULL, NULL, NULL),
('7bec5682-21c4-666f-a8db-e5d54223c257', 'Merchant11371', '1938219', '1970-01-01 00:00:01', 'VND', 'ORD_83930', 'SUCCESS', 'Abbott', '3513', '43489150', '1970-01-01 00:01:06', NULL),
('8d5006ce-799c-11eb-8a1f-00163e047e89', 'DucBinh1', '5956897', '2020-09-30 09:19:49', 'VND', 'ORD_43827', 'SUCCESS', 'Archer', '8276', '73577578', '1980-01-25 22:20:38', NULL),
('915fd181-799f-11eb-8a1f-00163e047e89', 'DucBinh2', '5956897', '2020-09-30 09:19:49', 'VND', 'ORD_43827', 'SUCCESS', 'Archer', '8276', '73577578', '1980-01-25 22:20:38', '2021-02-28 16:33:01'),
('b483ce3e-79a0-11eb-8a1f-00163e047e89', 'DucBinh2', '5956897', '2020-09-30 09:19:49', 'VND', 'ORD_43827', 'SUCCESS', 'Archer', '8276', '73577578', '1980-01-25 22:20:38', '2021-02-28 16:41:09'),
('bdaf4c25-79a0-11eb-8a1f-00163e047e89', 'DucBinh222', '5956897', '2020-09-30 09:19:49', 'VND', 'ORD_43827', 'SUCCESS', 'Archer', '8276', '73577578', '1980-01-25 22:20:38', '2021-02-28 16:41:24'),
('ed025e82-79aa-11eb-8a1f-00163e047e89', 'APITEST', '5000', '2021-02-28 16:53:16', 'VND', 'ORD_0000009', 'SUCCESS', 'NGUYEN VAN A', '0307', '970400xxxxxx0018', '2021-02-28 16:54:08', '2021-02-28 17:54:19');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;